APPClienteIt3/ViewModels/Imovel_Venda_Permuta_Aluguer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace APPClienteIt3.Models
{
    public class Imovel_Venda_Permuta_Aluguer
    {
        public int ID { get; set; }
        public string applicationUserID { get; set; }
        public int tipoImovelID { get; set; }

        [DisplayName("Tipo de Imovel")]
        public string tipoImovel { get; set; }
        public int localizacaoID { get; set; }

        [DisplayName("Local")]
        public string local { get; set; }

        [DisplayName("Latitude")]
        public string latitude { get; set; }

        [DisplayName("Longitude")]
        public string longitude { get; set; }

        [DisplayName("Área")]
        public float area { get; set; }

        public int fotoID { get; set; }
        public string fotoContent { get; set; }
        public string fotoContentType { get; set; }
    }
}

APPClienteIt3/Controllers/Imovel_Venda_Permuta_AluguerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using APPClienteIt3.Models;
using APPClienteIt3.Helpers;
using System.Net.Http;
using Newtonsoft.Json;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;


namespace APPClienteIt3.Controllers
{
    public class Imovel_Venda_Permuta_AluguerController : Controller
    {

        // GET: Imovel_Venda_Permuta_Aluguer
        public async Task<ActionResult> Index()
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Imovel_Venda_Permuta_Aluguer/");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var imovelVendaPermutaAluguer =
                JsonConvert.DeserializeObject<IEnumerable<Imovel_Venda_Permuta_Aluguer>>(content);
                return View(imovelVendaPermutaAluguer);
            }
            else
            {
                return RedirectToAction("Noauto", "Home");
            }
        }


        public async Task<IEnumerable<Imovel_Venda_Permuta_Aluguer>> getAll()
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Imovel_Venda_Permuta_Aluguer/");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var imovelVendaPermutaAluguer =
                JsonConvert.DeserializeObject<IEnumerable<Imovel_Venda_Permuta_Aluguer>>(content);
                return imovelVendaPermutaAluguer;
            }
            else
            {
                return null;
            }
        }

        // GET: Imovel_Venda_Permuta_Aluguer/Details/5
        public async Task<Imovel_Venda_Permuta_Aluguer> get(int? id)
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Imovel_Venda_Permuta_Aluguer/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var imovelVendaPermutaAluguer = JsonConvert.DeserializeObject<Imovel_Venda_Permuta_Aluguer>(content);

                return imovelVendaPermutaAluguer;
            }
            else
            {
                return null;
            }
        }

        // GET: Imovel_Venda_Permuta_Aluguer/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Imovel_Venda_Permuta_Aluguer/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var imovelVendaPermutaAluguer = JsonConvert.DeserializeObject<Imovel_Venda_Permuta_Aluguer>(content);
                if (imovelVendaPermutaAluguer == null) return HttpNotFound();
                return View(imovelVendaPermutaAluguer);
            }
            else
            {
                return RedirectToAction("Noauto", "Home");
            }
        }

        // GET: Imovel_Venda_Permuta_Aluguer/Create
        public async Task<ActionResult> Create()
        {
            await PopulateDropDownListTipoImovel(0);
            return View();
        }

        // POST: Imovel_Venda_Permuta_Aluguer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID, TipoImovelID, area, local, latitude, longitude")] Imovel_Venda_Permuta_Aluguer imovelVendaPermutaAluguer, HttpPostedFileBase upload)
        {
            try
            {

                if (upload != null && upload.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        imovelVendaPermutaAluguer.fotoContent = System.Text.Encoding.Default.GetString(reader.ReadBytes(upload.ContentLength));
                    }
                    
                    imovelVendaPermutaAluguer.fotoContentType = upload.ContentType;
                }

                var client = WebApiHttpClient.GetClient();
                string imovelVendaPermutaAluguerJSON = JsonConvert.SerializeObject(imovelVendaPermutaAluguer);
                HttpContent content = new StringContent(imovelVendaPermutaAluguerJSON,
                System.Text.Encoding.Unicode, "application/json");
                var response = await client.PostAsync("api/Imovel_Venda_Permuta_Aluguer", content);
                 if (response.IsSuccessStatusCode)
                  {
                      return RedirectToAction("Index");
                  }
                  else
                  {
                return RedirectToAction("Noauto", "Home");
                  }
            }
            catch
            {
                return RedirectToAction("Erro", "Home");
            }
        }

        // GET: Imovel_Venda_Permuta_Aluguer/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Imovel_Venda_Permuta_Aluguer/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var imovelVendaPermutaAluguer = JsonConvert.DeserializeObject<Imovel_Venda_Permuta_Aluguer>(content);
                if (imovelVendaPermutaAluguer == null) return HttpNotFound();

                await PopulateDropDownListTipoImovel(imovelVendaPermutaAluguer.tipoImovelID);
                imovelVendaPermutaAluguer.fotoContent = "";
                return View(imovelVendaPermutaAluguer);
            }
            return RedirectToAction("Noauto", "Home");
        }

        // POST: Imovel_Venda_Permuta_Aluguer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID, TipoImovelID, area, local, latitude, longitude")] Imovel_Venda_Permuta_Aluguer imovelVendaPermutaAluguer, HttpPostedFileBase upload)
        {
            try
            {

                if (upload != null && upload.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        imovelVendaPermutaAluguer.fotoContent = System.Text.Encoding.Default.GetString(reader.ReadBytes(upload.ContentLength));
                    }

                    imovelVendaPermutaAluguer.fotoContentType = upload.ContentType;
                }
                 
                var client = WebApiHttpClient.GetClient();
                string imovelVendaPermutaAluguerJSON = JsonConvert.SerializeObject(imovelVendaPermutaAluguer);
                HttpContent content = new StringContent(imovelVendaPermutaAluguerJSON,
                System.Text.Encoding.Unicode, "application/json");
                var response =
                await client.PutAsync("api/Imovel_Venda_Permuta_Aluguer/" + imovelVendaPermutaAluguer.ID, content);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Noauto", "Home");
                }
            }
            catch
            {
                return RedirectToAction("Erro", "Home");
            }
        }

        // GET: Imovel_Venda_Permuta_Aluguer/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Imovel_Venda_Permuta_Aluguer/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var imovelVendaPermutaAluguer = JsonConvert.DeserializeObject<Imovel_Venda_Permuta_Aluguer>(content);
                if (imovelVendaPermutaAluguer == null) return HttpNotFound();
                return View(imovelVendaPermutaAluguer);
            }
            return RedirectToAction("Noauto", "Home");
        }

        // POST: Imovel_Venda_Permuta_Aluguer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var client = WebApiHttpClient.GetClient();
                var response = await client.DeleteAsync("api/Imovel_Venda_Permuta_Aluguer/" + id);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {

APPClienteIt3/Views/Imovel_Venda_Permuta_Aluguer/Create.cshtml
@model APPClienteIt3.Models.Imovel_Venda_Permuta_Aluguer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<h4>Imóvel Venda/Permuta/Aluguer</h4>


@using (Html.BeginForm("Create", "Imovel_Venda_Permuta_Aluguer", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.local, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.local, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.local, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--Foto-->
        <div class="form-group">
            @Html.Label("Foto", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Foto" name="upload" />
            </div>
        </div>

        <!--Tipo de Imóvel-->
        <div class="control-group">
            <label class="control-label col-md-2" for="TipoImovelID">Tipo de Imóvel</label>
            <div class="col-md-2">
                @Html.DropDownList("TipoImovelID", String.Empty)
                @Html.ValidationMessageFor(model => model.tipoImovelID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APPClienteIt3/Views/Imovel_Venda_Permuta_Aluguer/Delete.cshtml
@model APPClienteIt3.Models.Imovel_Venda_Permuta_Aluguer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h4>Imóvel Venda/Permuta/Aluguer</h4>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Tipo de Imóvel
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipoImovel)
        </dd>

        <dt>
            Local
        </dt>

        <dd>
            @Html.DisplayFor(model => model.local)
        </dd>
        <dt>
            Latitude
        </dt>

        <dd>
            @Html.DisplayFor(model => model.latitude)
        </dd>
        <dt>
            Longitude
        </dt>

        <dd>
            @Html.DisplayFor(model => model.longitude)
        </dd>
        <dt>
            Área
        </dt>

        <dd>
            @Html.DisplayFor(model => model.area)
        </dd>

        @if (Model.fotoContent != null)
        {
            <dt>
                Foto
            </dt>
            <dd>
                <img src="~/Foto?id=@Model.fotoID" alt="foto" height="200" />
            </dd>
        }
        
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

APPClienteIt3/Views/Imovel_Venda_Permuta_Aluguer/Details.cshtml
@model APPClienteIt3.Models.Imovel_Venda_Permuta_Aluguer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<h4>Imóvel Venda/Permuta/Aluguer</h4>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Local
        </dt>

        <dd>
            @Html.DisplayFor(model => model.local)
        </dd>

        <dt>
            Tipo de Imóvel
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipoImovel)
        </dd>

        <dt>
            Área
        </dt>

        <dd>
            @Html.DisplayFor(model => model.area)
        </dd>

        @if (Model.fotoContent != null)
        {
            <dt>
                Foto
            </dt>
            <dd>
                <img src="~/Foto?id=@Model.fotoID" alt="foto" height="200" />
            </dd>
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

APPClienteIt3/Views/Imovel_Venda_Permuta_Aluguer/Edit.cshtml
@model APPClienteIt3.Models.Imovel_Venda_Permuta_Aluguer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<h4>Imóvel para Venda/Permuta/Aluguer</h4>


@using (Html.BeginForm("Edit", "Imovel_Venda_Permuta_Aluguer", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.local, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.local, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.local, "", new { @class = "text-danger" })
                @Html.Hidden("localizacaoID", Model.ID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.fotoContent != null)
        {
            <dt>
                Foto
            </dt>
            <dd>
                <img src="~/Foto?id=@Model.fotoID" alt="foto" height="200" />
            </dd>
        }

        <div class="form-group">
            @Html.Label("Foto", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Foto" name="upload" />
            </div>
        </div>
        <!--Tipo de Imóvel-->
        <div class="control-group">
            <label class="control-label col-md-2" for="tipoImovelID">Tipo de Imóvel</label>
            <div class="col-md-2">
                @Html.DropDownList("TipoImovelID", String.Empty)
                @Html.ValidationMessageFor(model => model.tipoImovelID)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APPClienteIt3/Views/Imovel_Venda_Permuta_Aluguer/Index.cshtml
@model IEnumerable<APPClienteIt3.Models.Imovel_Venda_Permuta_Aluguer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<h4>Imóvel Venda/Permuta/Aluguer</h4>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.tipoImovel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.area)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.local)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.latitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.longitude)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.tipoImovel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.area)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.local)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.longitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.latitude)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }
</table>