AdministradorIT4/APPAdministrador/Controllers/AlertasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using APPAdministrador.ViewModels;

namespace APPAdministrador.Controllers
{
    public class AlertasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Alertas
        public async Task<ActionResult> Index()
        {
            return View(await db.Alertas.ToListAsync());
        }

        // GET: Alertas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alerta alerta = await db.Alertas.FindAsync(id);
            if (alerta == null)
            {
                return HttpNotFound();
            }
            return View(alerta);
        }

        // POST: Alertas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,applicationUserID,intervaloAlerta")] Alerta alerta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(alerta).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(alerta);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdministradorIT4/APPAdministrador/Controllers/Anuncio_CompraController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using APPAdministrador.ViewModels;

namespace APPAdministrador.Controllers
{
    public class Anuncio_CompraController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Anuncio_Compra
        public async Task<ActionResult> Index()
        {
            ViewBag.Anuncios_Compra = db.Anuncio_Compra.ToList();
            ViewBag.Anuncios_Venda = db.Anuncio_Venda.ToList();
            return View();
        }

        // GET: Anuncio_Compra/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Anuncio_Compra anuncio_Compra = await db.Anuncio_Compra.FindAsync(id);
            if (anuncio_Compra == null)
            {
                return HttpNotFound();
            }
            return View(anuncio_Compra);
        }

        // POST: Anuncio_Compra/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,ImovelID,applicationUserID,tipoImovelID,tipoImovel,localizacaoID,local,latitude,longitude,areaMin,areaMax,precoMin,precoMax,valido,MediadorID,AnuncioVendaID")] Anuncio_Compra anuncio_Compra)
        {
            if (ModelState.IsValid)
            {
                db.Entry(anuncio_Compra).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(anuncio_Compra);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdministradorIT4/APPAdministrador/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - APPAdministrador</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("APP Administrador", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Intervalos de Alertas", "Index", "Alertas")</li>
                    <li>@Html.ActionLink("Carregar de Ficheiro", "Create", "FicheiroViewModels")</li>
                    <li>@Html.ActionLink("Intervalo de Correspondências", "Index", "Anuncio_Compra")</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ARQSI</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>